name: Fetch and Update Content

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - main

jobs:
  fetch-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios

      - name: Fetch content
        run: |
          node -e "const axios = require('axios'); axios.get('https://1v1.lol/').then(response => { require('fs').writeFileSync('content.html', response.data); }).catch(error => { console.error('Error fetching data:', error); });"

      - name: Commit and push changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add content.html
          git commit -m "Update content from 1v1.lol"
          git push
